# ── checklist_auto.R ──────────────────────────────────────────────────────────
# Automated validator for R scripts generated by the r-high-fidelity-viz skill.
# Checks the mechanically-verifiable subset of the 26-point quality checklist
# in plan.md Section 11.
#
# Usage:
#   source("tests/checklist_auto.R")
#   validate_script("examples/01_scatter_regression.R")
#   validate_all("examples/")
# ─────────────────────────────────────────────────────────────────────────────

# ── Rule definitions ──────────────────────────────────────────
.RULES <- list(
  list(
    id      = "R-01",
    desc    = "library() calls present",
    type    = "error",
    pattern = "library\\(",
    negate  = FALSE
  ),
  list(
    id      = "R-02",
    desc    = "ggsave() call present",
    type    = "error",
    pattern = "ggsave\\(",
    negate  = FALSE
  ),
  list(
    id      = "R-03",
    desc    = "width argument in ggsave()",
    type    = "error",
    pattern = "width\\s*=",
    negate  = FALSE
  ),
  list(
    id      = "R-04",
    desc    = "height argument in ggsave()",
    type    = "error",
    pattern = "height\\s*=",
    negate  = FALSE
  ),
  list(
    id      = "R-05",
    desc    = "units argument in ggsave()",
    type    = "error",
    pattern = "units\\s*=",
    negate  = FALSE
  ),
  list(
    id      = "R-06",
    desc    = "dpi argument in ggsave()",
    type    = "error",
    pattern = "dpi\\s*=",
    negate  = FALSE
  ),
  list(
    id      = "R-07",
    desc    = "No setwd() calls",
    type    = "error",
    pattern = "setwd\\(",
    negate  = TRUE
  ),
  list(
    id      = "R-08",
    desc    = "No install.packages() calls",
    type    = "error",
    pattern = "install\\.packages\\(",
    negate  = TRUE
  ),
  list(
    id      = "R-09",
    desc    = "Colorblind-safe palette referenced",
    type    = "error",
    pattern = paste(c(
      "viridis", "scale_fill_viridis", "scale_color_viridis",
      "scale_color_npg", "scale_fill_npg",
      "scale_color_aaas", "scale_fill_aaas",
      "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7",
      "#F0E442", "okabe", "Okabe",
      "scale_fill_brewer", "scale_color_brewer",
      "colorblind", "plasma", "magma", "inferno", "cividis"
    ), collapse = "|"),
    negate  = FALSE
  ),
  list(
    id      = "R-10",
    desc    = "labs(title = ...) present",
    type    = "error",
    pattern = "labs\\s*\\(",
    negate  = FALSE
  ),
  list(
    id      = "R-11",
    desc    = "Axis labels (x or y) in labs()",
    type    = "error",
    pattern = "labs\\s*\\([^)]*[xy]\\s*=",
    negate  = FALSE
  ),
  list(
    id      = "R-12",
    desc    = "sessioninfo::session_info() present (reproducibility)",
    type    = "warning",
    pattern = "session_info|sessionInfo",
    negate  = FALSE
  )
)

# ── Core validator ────────────────────────────────────────────
validate_script <- function(path) {
  if (!file.exists(path)) {
    cat(sprintf("ERROR: file not found: %s\n", path))
    return(invisible(FALSE))
  }

  content <- paste(readLines(path, warn = FALSE), collapse = "\n")
  errors   <- 0L
  warnings <- 0L

  cat(sprintf("\n── Validating: %s ─────────────────────────\n", basename(path)))

  for (rule in .RULES) {
    matched  <- grepl(rule$pattern, content, perl = TRUE)
    passed   <- if (rule$negate) !matched else matched
    status   <- if (passed) "PASS" else toupper(rule$type)
    icon     <- if (passed) "✓" else if (rule$type == "error") "✗" else "⚠"

    cat(sprintf("  %s [%s] %s — %s\n", icon, rule$id, status, rule$desc))

    if (!passed && rule$type == "error")   errors   <- errors   + 1L
    if (!passed && rule$type == "warning") warnings <- warnings + 1L
  }

  cat(sprintf("\nResult: %d error(s), %d warning(s)\n", errors, warnings))
  cat(if (errors == 0L) "PASSED\n" else "FAILED\n")

  invisible(errors == 0L)
}

# ── Batch validator ───────────────────────────────────────────
validate_all <- function(dir = "examples/") {
  scripts <- list.files(dir, pattern = "\\.R$", full.names = TRUE)

  if (length(scripts) == 0L) {
    cat(sprintf("No .R files found in %s\n", dir))
    return(invisible(FALSE))
  }

  results <- vapply(scripts, validate_script, logical(1L))

  cat(sprintf(
    "\n══ Summary: %d/%d scripts passed ══\n",
    sum(results), length(results)
  ))

  invisible(all(results))
}

# ── Run automatically if called via Rscript ───────────────────
if (!interactive()) {
  args <- commandArgs(trailingOnly = TRUE)
  if (length(args) == 0L) {
    ok <- validate_all("examples/")
  } else {
    ok <- all(vapply(args, validate_script, logical(1L)))
  }
  quit(status = if (ok) 0L else 1L)
}
